### ISSUE TITLE
Discussion about the framework

### ISSUE THREAD

**Issue by AssociazioneRousseau** [associazione-rousseau/camelot-flutter#1]
Given the resources and the time, we want to user Flutter to build a cross platform app and try to fork the code between Android and iOS only if strictly required.

It would be nice to speak with all the developers to make sure we are aligned on that.

**Comment by emanuelconunaemme** [comment]
I really think we should go with Flutter for a faster development. After comparing all the alternative, this seems the most promising cross platform framework, which is going to kill React Native.

Of course, the native implementations are better, but, currently I don't think all the pros will justify maintaining two codebases.

For all the critical parts, we can always "fork" and have two native implementations. For example for the single sign on we use [Keycloak](https://www.keycloak.org). It . doesn't provide Flutter libraries but only natives. Needless to say, the login is a really critical part. We can have two native implementations of this. On the other hand, we can be really fast on the UI part.

I'd like to hear your opinions...

**Comment by gedamial** [comment]
I like the idea of using Flutter. It's fast, relatively easy to work with and, in my opinion, speeds up the development process.

**Comment by panthe** [comment]
I think developing in Flutter can be the better choice this moment. Not only for the speed but for the type of language, Dart that is natively typed and very simple.

**Comment by john79nl** [comment]
why not using unity?

**Comment by flashboss** [comment]
Hi all, happy to see start a new opensource project. Actually I'm working for an application for online elections. I have a ready backend to manage the votes. It is a java / spring based app working with json. You can find it here and study it if it can be useful: https://github.com/vige-vota/voting . Here the complete project: http://vota.vige.it , https://github.com/vige-vota

**Comment by fpagano** [comment]
I met Flutter's creators in San Francisco last year and I was immediatly engaged with this new framework. Previously I use Ionic for my mobile apps, but now I am using Flutter either for Android either for iOs.

**Comment by giovapanasiti** [comment]
I've fallen in love for Flutter since the first time I've used it. At the moment I have a couple of app already in production using this framework. Never found a problem nor a drawback using it over other solutions.

**Comment by fpagano** [comment]
> 
> 
>Never found a problem nor a drawback using it over other solutions.

this is not  completely true, when you use plugins you may encounter some difficulties and incompatibilies

**Comment by giovapanasiti** [comment]
> this is not completely true, when you use plugins you may encounter some difficulties and incompatibilies

It really depends on which plugin you are talking about. Of course third parties plugins which rely on a single developer may have some issues but if you are wise enough you don't want to rely on such plugins on a large scale project like this.

**Comment by DarioLondon** [comment]
I have never used Flutter before but I can see some benefits for one codebase, however having all the backend ready shouldn't we divide the project in IOS , Android and Web?

**Comment by emanuelconunaemme** [comment]
@flashboss thank you for the reference. The project seems really well structured, although we already have the backend fully implemented since the First Round of the "Europarlamentarie". We have the frontend implemented and we are trying to implement the mobile app.

**Comment by emanuelconunaemme** [comment]
So, flutter it is (with [Provider](https://pub.dev/packages/provider) architecture)! Closing the issue!
