### ISSUE TITLE
Azione Logout non eseguita su test app Rousseau X

### ISSUE THREAD

**Issue by marcodadamo** [associazione-rousseau/camelot-flutter#185]
Dopo aver eseguito l'accesso all'app, volendo eseguire successivamente l'azione di disconnessione sul pulsante Logout, ho riscontrato che nella riapertura dell'applicazione l'account non è stato disconnesso. 
![IMG_20201018_081008](https://user-images.githubusercontent.com/56562822/96360058-9b29e200-1119-11eb-8293-bed5f08d5aa5.png)

**Comment by emanuelconunaemme** [comment]
Grazie mille @marcodadamo. Controlliamo subito!

**Comment by emanuelconunaemme** [comment]
@marcodadamo ho risolto il problema. In pratica falliva il delete del token a causa di una configurazione errata. Ho risolto il problema. La prossima settimana, non appena viene approvata la release da google dovresti ricevere un aggiornamento con il fix. Chiudo il task e ti ringrazio per la segnalazione.
