### ISSUE TITLE
Profile 2.0

### ISSUE THREAD

**Issue by emanuelconunaemme** [associazione-rousseau/camelot-flutter#198]

**Comment by bhack** [comment]
What is the sorting order in the web application query https://rousseau.movimento5stelle.it/profiles? 
I think it is highly unfair as the top positions are overexposed and this could also create a chain bias over "Mi fido" feature at https://github.com/associazione-rousseau/camelot-flutter/issues/201 . 

We need to have a random or at least a random weighted order to be fair.

These days we are all talking about fairness and diversity in AI, digital platforms etc. I don't think that we are in a position to ignore the digital bias that we create ourself on the platform that we are buildling and the code we commit in the frontend and in the private backed.

**Comment by emanuelconunaemme** [comment]
@bhack empirically (since I didn't work on the backend) I can tell that most of the profiles on the first page are randomly selected. There are few that are highly ranked are also selected randomly. Try to refresh the page and you can see that. What do you think? Would you go for a fully random generation giving no advantages at all to the one that have a high score?

**Comment by bhack** [comment]
I've tested with different devices, anon browser tab and shift+F5 and the top ones seems to me always the same faces.
It is a backend feature? Probably, but this is going to impact also the mobile application. 

As always it is hard to separate frontend/backend feature design especially cause I don't see an alternative sort menu in the web UX so I don't know if the backend API is ready for other type of sorts in the query  or it will impact also your mobile app as it is the only one.

You can write a single line `diff` shell script yourself to parse the `slug:` in the page output between two calls.

Personally as many profiles in the TOP positions have already a great media exposure for their role they don't need to keep a positional advantage in the profile page also to not feed self-serving popularity with "Mi fido".
 
To promote diversity I will like a random query but I could accept a fast weighted random if the weight sampling it is transparent to all the members.

As you see not all the technical-political choices could be defined within the statute perimeter and this is why it is fundamental to open a technical political discussion forum as I am suggesting at https://github.com/associazione-rousseau/camelot-flutter/issues/192.

We need to involve more members that are registered to the Rosseau platform and so to the M5S  without the Github account technical barrier.

I bet that many registered users will support you to the self-modreation activites that are daily required.
