### ISSUE TITLE
Setup Release on iTunes

### ISSUE THREAD

**Issue by emanuelconunaemme** [associazione-rousseau/camelot-flutter#21]

**Comment by aledeniz** [comment]
@emanuelconunaemme I reckon it makes more sense for someone from @AssociazioneRousseau to join the organisation to the [Apple Developer Program](https://developer.apple.com/it/support/compare-memberships/). 

By the look of it, Apple doesn't offer a fee waiver for the Apple Developer Program to the Italian non profit entities. They didn't even seem to have translated [the relevant page](https://developer.apple.com/it/support/membership-fee-waiver/).
I wonder if it may be worth for someone from @AssociazioneRousseau to contact Apple Italia, to inquire about the rationale (it is not really about the yearly €99, I just don't get why an Italian no profit organisation shouldn't be treated like a Brazilian or a Japanese one).

**Comment by aledeniz** [comment]
@emanuelconunaemme also, someone from @AssociazioneRousseau should perform a duns lookup, to ensure they have got a D-U-N-S Number, and if not request it from Dun & Bradstreet (D&B). It should be free. More info from Apple [here](https://developer.apple.com/support/D-U-N-S/).

This is the link for the lookup:

https://developer.apple.com/enroll/duns-lookup/#!/search

**Comment by bhack** [comment]
Pinpoint flutter doc https://flutter.dev/docs/deployment/ios

**Comment by emanuelconunaemme** [comment]
Thanks. Our backoffice is working on it!
