### ISSUE TITLE
Setup Release on PlayStore

### ISSUE THREAD

**Issue by emanuelconunaemme** [associazione-rousseau/camelot-flutter#22]

**Comment by bhack** [comment]
Pinpoint doc https://flutter.dev/docs/deployment/android

**Comment by emanuelconunaemme** [comment]
@bhack do you want to work on that? That would be really helpful at this state and really appreciated.

**Comment by bhack** [comment]
What is missing currently? 
Cause I suppose that for signing it is better that you do on your keys.
